### ISSUE TITLE
Ingresar 4 registros de Personas, C/U

### ISSUE THREAD

**Issue by jmirsteinban** [jmirsteinban/PFP5#10]
Ingresar 4 registros de Personas, C/U

Donde: **Tabla: personas**

****
Listos;
- [x] @Vgaby 
- [x] @jmirsteinban 
- [x] @fpicadov 
- [x] @slherra27

**Comment by jmirsteinban** [comment]
Listo mi parte, commit [c307e5](https://github.com/jmirsteinban/PFP5/commit/c307e527bbd1e79863de0571e64c57d2ee7f51a7)

**Comment by Vgaby** [comment]
Listo mis registros, commit 6b4448
